models.py
from datetime import datetime

from exts import db

class UserModel(db.Model):

    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(200), nullable=False, unique=True)
    username = db.Column(db.String(200), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)
    join_time = db.Column(db.DateTime, default=datetime.now)

class QuestionModel(db.Model):
    __tablename__ = 'question'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.String(2000), nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    author_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    author = db.relationship('UserModel', backref='questions')

class AnswerModel(db.Model):

    __tablename__ = 'answer'
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(8000), nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    question_id = db.Column(db.Integer, db.ForeignKey('question.id'))
    author_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    author = db.relationship('UserModel', backref='answers')
    question = db.relationship('QuestionModel', backref=db.backref('answers', order_by=create_time.desc()))

blueprints/forms.py
import wtforms
from wtforms.validators import length, email, EqualTo

from models import UserModel

class LoginForm(wtforms.Form):
    email = wtforms.StringField(validators=[email()])
    password = wtforms.StringField(validators=[length(6, 20)])

class RegisterForm(wtforms.Form):
    email = wtforms.StringField(validators=[email()])
    captcha = wtforms.StringField(validators=[length(1, 20)])
    username = wtforms.StringField(validators=[length(1, 20)])
    password = wtforms.StringField(validators=[length(6, 20)])
    password_confirm = wtforms.StringField(validators=[EqualTo('password')])

    #判断是否有重复email
    def validate_email(self, field):
        email = field.data
        result = UserModel.query.filter_by(email=email).first()
        if result:
            raise wtforms.ValidationError('存在email')

class QuestionForm(wtforms.Form):
    title = wtforms.StringField(validators=[length(1, 50)])
    content = wtforms.StringField(validators=[length(min=5)])

class AnswerForm(wtforms.Form):
    content = wtforms.StringField(validators=[length(min=1)])

app.py
from flask import Flask, g, session
from flask_migrate import Migrate

from exts import db, mail
import config
from blueprints import qa_bp, user_bp
from models import UserModel, QuestionModel

#配置app 和 blueprint
app = Flask(__name__)
app.config.from_object(config)
app.register_blueprint(qa_bp)
app.register_blueprint(user_bp)

@app.before_request
def check():
    if session.get('user_id'):
        try:
            user = UserModel.query.filter_by(id = session['user_id']).first()
            g.user = user
        except:
            g.user = None
    else:
        g.user = None

@app.context_processor
def cp():
    if g.user:
        return {'user':g.user}
    else:
        return {}


#配置数据库
db.init_app(app)
migrate = Migrate(app, db)

#配置邮箱
mail.init_app(app)

if __name__ == '__main__':
    app.run()

blueprints/__init__.py
from .qa import bp as qa_bp
from .user import bp as user_bp

blueprints/qa.py
from datetime import datetime

from flask import Blueprint, render_template, request, g, \
    redirect, url_for
from sqlalchemy import or_

from exts import db
from decorators import login_required
from models import QuestionModel, AnswerModel
from .forms import AnswerForm

bp = Blueprint('qa', __name__, url_prefix='/')


@bp.route('/')
def index():
    questions = QuestionModel.query.filter_by().all()
    if questions:
        context = {'questions': questions}
        return render_template('index.html', **context)
    else:
        return render_template('index.html')


@bp.route('/question/<int:question_id>')
def question_detail(question_id):
    question = QuestionModel.query.get(question_id)

    return render_template('detail.html', question=question, answers=question.answers,
                           answers_num=len(question.answers))


@bp.route('/question/<int:question_id>/answer', methods=['POST'])
@login_required
def upload_answer(question_id):
    form = AnswerForm(request.form)
    # 需要登录
    if form.validate():
        content = form.content.data
        create_time = datetime.now()
        author_id = g.user.id
        answer_model = AnswerModel(content=content, create_time=create_time, question_id=question_id,
                                   author_id=author_id)
        db.session.add(answer_model)
        db.session.commit()
    return redirect(url_for('qa.question_detail', question_id=question_id))

@bp.route('/question/<int:question_id>/delete_answer<int:answer_id>')
@login_required
def delete_answer(question_id, answer_id):
    AnswerModel.query.filter_by(id=answer_id).delete()
    db.session.commit()
    return redirect(url_for('qa.question_detail', question_id=question_id))

@bp.route('/search')
def search():
    q = request.args.get('q') #关键字 string
    questions = QuestionModel.query.filter(or_(QuestionModel.title.contains(q),
                                   QuestionModel.content.contains(q)))
    return render_template('index.html', questions=questions)

blueprints/user.py
from datetime import datetime

from flask import Blueprint, render_template, request, redirect, \
    url_for, session, flash, g
from flask_mail import Message
from werkzeug.security import generate_password_hash, check_password_hash

from exts import mail
from .forms import RegisterForm, LoginForm, QuestionForm
from models import db, UserModel, QuestionModel
from decorators import login_required

bp = Blueprint('user', __name__, url_prefix='/user')

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('user.login'))

@bp.route('/login', methods=['POST', "GET"])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    elif request.method == 'POST':
        print(request.form)
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password, password):
                session['user_id'] = user.id
                return redirect(url_for('qa.index'))
        flash('邮箱或者密码错误')
        return render_template('login.html')

@bp.route('/register', methods=['POST', "GET"])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    elif request.method == 'POST':
        form = RegisterForm(request.form)
        if form.validate():
            #保存到数据库
            email = form.email.data
            username = form.username.data
            password = generate_password_hash(form.password.data)
            user = UserModel(email=email, username=username, password=password,
                             join_time=datetime.now())
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('user.login'))
        else:
            return render_template('register.html')

@bp.route('/mail')
def send_mail():
    message = Message('邮箱测试',
                      recipients=['3574068495@qq.com'],
                      body='这是邮件测试')
    mail.send(message)
    return "success"

@bp.route('/question/public', methods=['GET', 'POST'])
@login_required
def public_question():
    if request.method == 'GET':
        return render_template('public_question.html')
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content,
                          create_time=datetime.now(), author_id=g.user.id)

            db.session.add(question)
            db.session.commit()
            return redirect('/')
        else:
            return render_template('public_question.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.css') }}">
{#    <link rel="stylesheet" href="{{ url_for('static', filename='css/init.css') }}">#}
    {% block head %} {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">知了问答</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('user.public_question')}}">发布问答</a>
                </li>
                <li class="nav-item ml-3">
                    <form class="form-inline my-2 my-lg-0" method="get" action="{{ url_for('qa.search') }}">
                        <input class="form-control mr-sm-2" type="search" placeholder="关键字"
                               aria-label="Search" name="q">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user %}
                    <li class="nav-item">
                    <span class="nav-link">{{user.username}} <span class="sr-only">(current)</span></span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('user.logout')}}">注销</a>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.login') }}">登陆 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block body %} {% endblock %}
</div>

</body>
</html>

templates/detail.html
{% extends "base.html" %}
{% block title %}
    问答详情页面
{% endblock %}
{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-8">
            <h3 class="page-title">{{ question.title }}</h3>
            <p class="question-info">
                <span>作者：{{ question.author.username }}</span>
                <span>时间：{{ question.create_time }}</span>
            </p>
            <hr>
            <p class="question-content">
                {{ question.content }}
            </p>
            <hr>
            <h4 class="comment-group-title">
                评论({{ answers_num }})
            </h4>
            <form action="{{ url_for('qa.upload_answer', question_id=question.id) }}" method="post">
                <div class="form-group">
                            <textarea name="content" cols="30" rows="10" class="form-control"
                                      placeholder="请输入评论"></textarea>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">发布</button>
                </div>
            </form>
            {% for answer in answers %}
                <ul class="comment-group">
                    <li>
                        <div class="user-info">
                            <img src="{{ url_for('static', filename='1.jpg') }}"
                                 width="50px" height="50px">
                            <span class="username">{{ answer.author.username }}</span>
                            <span class="create-time">{{ answer.create_time }}</span>
                        </div>
                        <p class="comment-content">{{ answer.content }}</p>
                        <form action="{{ url_for('qa.delete_answer',
                              question_id = question.id, answer_id = answer.id) }}" method="get">
                            <div class="form-group">
                                <button class="btn btn-primary" type="submit">删除</button>
                            </div>
                        </form>
                    </li>
                </ul>
            {% endfor %}
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}
    知了问答-首页
{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
    <div class="container" align="middle">
    <iframe src="//player.bilibili.com/player.html?aid=764123508&bvid=BV17r4y1y7jJ&cid=440891352&page=29"
            scrolling="no" border="0" frameborder="no" framespacing="0" height="480" width="800"
            allowfullscreen="true"> </iframe>
    </div>

    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col-8">
            {% for question in questions %}
                <ul class="question-ul">
                    <li>
                        <div class="side-question">
                            <img src="{{ url_for('static', filename='1.jpg') }}" alt="照片"
                                 width="50px" height="50px">
                        </div>
                        <div class="question-main">
                            <p class="question-title">
                                <a href="{{ url_for('qa.question_detail', question_id=question.id) }}">{{ question.title }}</a>
                            </p>
                            <q class="question-content">
                                {{ question.content }}
                            </q>
                            <q class="question-detail">
                                <span class="question-author">
                                    {{ question.author.username }}
                                </span>
                                <span class="question-time">
                                    {{ question.create_time }}
                                </span>
                            </q>
                        </div>
                    </li>
                </ul>
            {% endfor %}
            </div>
            <div class="col"></div>
        </div>
    </div>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}
    登陆
{% endblock %}
{% block body %}
    <div class="row mt-5">
        <div class="col"></div>
        <div class="col">
            <form action="{{ url_for('user.login') }}" method="POST">
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱</label>
                    <input type="email" class="form-control"  name="email">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" name="password">
                </div>
                {% for message in get_flashed_messages() %}
                    <div class="form-group">
                        <div class="text-danger">
                            {{ message }}
                        </div>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary btn-block">立即登陆</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/public_question.html
{% extends "base.html" %}
{% block title %}
    发布问答
{% endblock %}
{% block body %}
    <div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-6">
        <form action="{{ url_for('user.public_question') }}" method="post">
            <div class="form-group">
                <input type="text" class="form-control" name="title" placeholder="请输入标题">
            </div>
            <div class="form-group">
                <textarea name="content" cols="30" rows="10" class="form-control"
                          placeholder="请输入正文"></textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">发布</button>
            </div>
        </form>
    </div>
    <div class="col"></div>
    </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block title %}
    注册
{% endblock %}
{% block body %}
    <div class="row mt-5">
        <div class="col"></div>
        <div class="col">
            <form action="{{ url_for('user.register') }}" method="post">
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱</label>
                    <input type="email" class="form-control"  aria-describedby="emailHelp" name="email">
                    <small  class="form-text text-muted">我们不会将邮箱告诉其他人。</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">验证码</label>
                    <div class="input-group">
                        <input type="text" class="from-control" name="captcha">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button">获取验证码</button>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">用户名</label>
                    <input type="text" class="form-control"  name="username">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" name="password">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">确认密码</label>
                    <input type="password" class="form-control" name="password_confirm">
                </div>
                <button type="submit" class="btn btn-primary btn-block">立即注册</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}